### ISSUE TITLE
Publish the HEAD to `npm`

### ISSUE THREAD

**Issue by yxliang01** [winfinit/mongodb-download#24]
Hello @winfinit , would you like to publish the HEAD to `npm`? Since the current one at npm(version `2.2.3`) has bug for debian 9 (it treats Debian 9 a legacy system). After publishing this one, would you like to update the dependent version of this library for `mongodb-prebuilt` and `mockgoose`?

Thanks a lot!

**Comment by david-cho-lerat-HL2** [comment]
Yes, pretty please? Got bit by this again and couldn't understand why at first, as PR #20 had been merged. This should really work, now: Debian 8.1 was released on June 6th, 2015 - this means that `mongodb-download` has been broken on Debian ever since? Or was the Mongo download for 8.1+ released recently? Anyway, it would really be great if you could build from HEAD and publish the built module, please. Thanks!

**Comment by winfinit** [comment]
Sorry folks for this delay, if I understood correctly, all we needed to do is a publish to NPN, it is done now.
